
## Deployment
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-go-app
        image: istio-adapter-demo:1.0
        ports:
        - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  ports:
  - name: http-port
    port: 8090
    targetPort: 8090
  selector:
    app: demo-app
  type: LoadBalancer

---
